ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]


= 북마크 관련 API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:toc-title: Table of Contents
:sectlinks:


BOJ Bookmark Extension 크롬 확장 프로그램의 +
북마크 등록,수정 및 조회와 관련된 API 문서입니다.


[[Bookmark-전체-조회]]
== 모든 북마크 조회
=== `GET /api/bookmark/list`
유저가 등록한 모든 북마크를 반환합니다. +
북마크가 존재하지 않으면 빈 배열을 반환합니다. +
ex) { "bookmarkList" : [] }

operation::bookmark/list[snippets='http-request,http-response,response-fields']

[[Bookmark-오늘-풀어야할-문제-목록-조회]]
== 오늘 풀어야할 문제 목록 조회
=== `GET /api/bookmark/list/today`
유저가 오늘 풀어야 할 문제를 반환합니다. +
북마크가 존재하지 않으면 빈 배열을 반환합니다. +
ex) { "problemList" : [] }

operation::bookmark/list-today[snippets='http-request,http-response,response-fields']

[[Bookmark-북마크-등록]]
== 북마크 등록
=== `POST /api/bookmark`
유저가 새로 북마크를 등록합니다. +
응답 확인만 가능( status : OK )

operation::bookmark/add[snippets='http-request,request-fields,http-response']

[[Bookmark-북마크-수정]]
== 북마크 수정
=== `PUT /api/bookmark`
유저가 등록되어 있는 북마크를 수정합니다. +
응답 확인만 가능( status : OK )

operation::bookmark/update[snippets='http-request,request-fields,http-response']


[[Bookmark-북마크-여부-확인]]
== 북마크 여부 확인
=== `GET /api/bookmark/{problemNum}`
유저의 해당 문제의 북마크 여부를 확인합니다.

operation::bookmark/check[snippets='http-request,path-parameters,http-response,response-fields']

[[Bookmark-북마크-취소]]
== 북마크 취소
=== `DELETE /api/bookmark/{problemNum}`
유저가 등록되있는 북마크를 취소합니다. +
응답 확인만 가능( status : OK )

operation::bookmark/delete[snippets='http-request,path-parameters,http-response']
