server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}


  profiles:
    active: ${PROFILE}
    group:
      local:
        - h2
        - security
      prod:
        - mysql
        - security

---
spring:
  profiles:
    active:
      on-profile: local
---
spring:
  profiles:
    active:
      on-profile: prod