spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        mime:
          charset: UTF-8
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true


jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: 3600000 # 1시간
    header: Authorization
  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-refresh


  admin:
    password: ${JWT_ADMIN_PASSWORD}

#메일 서버 참고
